include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_unnecessary_containers
    - prefer_single_quotes
    - avoid_print
    - prefer_final_locals
    - avoid_init_to_null
    - empty_constructor_bodies
    - always_declare_return_types
    - require_trailing_commas
